baseURL = 'https://jonesrussell.github.io/hugo-blog/'
languageCode = 'en-us'
title = 'Web Developer Blog | A resource for web developers, I use modern technologies, best practices, and personal experiences. Explore guides on Laravel, Golang, Docker, and more.'
theme = 'hugo-book'
